src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AuthorRepository::class)
 */
class Author
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $LastName;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DeathDate;

    /**
     * @ORM\OneToMany(targetEntity=Book::class, mappedBy="Author")
     */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getDeathDate(): ?\DateTimeInterface
    {
        return $this->DeathDate;
    }

    public function setDeathDate(?\DateTimeInterface $DeathDate): self
    {
        $this->DeathDate = $DeathDate;

        return $this;
    }

    /**
     * @return Collection|Book[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->setAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->removeElement($book)) {
            // set the owning side to null (unless already changed)
            if ($book->getAuthor() === $this) {
                $book->setAuthor(null);
            }
        }

        return $this;
    }
    

}

templates/auteurs.html.twig
{% extends 'base.html.twig' %}
{# j'extend mon fichier "base" pour que symfony renvoie mon squellette préalablement configuré sur cette page Html #}
{# j'ouvre mon bloc title pour signifier que cest a cet endroit que je vais modifier une donnée dans mon squelette #}
{% block title%}
    Liste des auteurs
{% endblock title %}
    {% block main %}
        <article>
            <h2 class="center">Liste des Auteurs</h2>
            {# je cree une boucle for pour passer sur chaque element de mon tableau livres et pour qu'il complete par les elements demandés #}
            {% for author in authors %}
                <div class="livre border">
                    <h3 class="center"> {{ author.firstName }}</h3>
                    <p class="center"> {{ author.LastName }}</p>
                    <em class="center date">Mort le :{{ author.DeathDate|date('d/m/y')}}</em>
                    <br>
                    {#   <div class="divImg">
                <img class="imgList" src="{{livre.img}}" alt="{{ livre.title }}">
                        </div>
                    #}
                    <a class="aLivres border block" href="{{ path('auteur', {"id":author.id}) }}">Voir Plus</a>
                </div>
            {% endfor %}
            {# je referme ma boucle for #}
        </article>
    {% endblock main %}

templates/author_create.html.twig
{% extends "base.html.twig" %}

{% block title %}
Auteur ajouté
{% endblock title %}
{% block main %}
    <p>Cet auteur a bien été ajouté !</p>
{% endblock main %}

templates/base.html.twig
{# je prépare un squelette html de ma page qui contient mon header, mon footer, en indiquant des trous et les elements du squelette qui sont susceptible de varier au cours des pages #}
{# grace a des "Blocs" #}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href={% block css %}"{{ asset('style.css') }}"{% endblock css %}>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title> {%block title %} Document {% endblock title %} </title>
</head>
<header class="Header">
    <nav class="menuHeader border">
        <ul class="flex ulHeader">
            <li class="liHeader border">
                <a class="aHeader" href="{{ path('home') }}">Home</a>
            </li>
            <li class="liHeader border">
                <a class="aHeader" href="{{ path('admin_livres') }}">Livres</a>
            </li>
            <li class="liHeader border">
                <a class="aHeader" href="{{ path('admin_auteurs') }}">Auteurs</a>
            </li>
        </ul>
        <form action="{{ path('admin_search_books') }}">
            <input type="text" name="query">
            <input type="submit">
        </form>

    </nav>
</header>
<body class="body">
    {% block main %}
    {% endblock main %}
</body>
</html>
<footer>
</footer>

templates/book_create.html.twig
{% extends "base.html.twig" %}
{% block title %}
    Livre ajouté
{% endblock title %}
{% block main %}
    <p>Ce livre a bien été ajouté !</p>
{% endblock main %}

templates/home.html.twig
{% extends 'base.html.twig' %}
{% block title%}
    Bienvenue
{% endblock title %}
{% block main %}
    <h1 class="h1"> Bienvenue Sur ma bibliotheque </h1>
    <h3 class="center">Derniers ajouts:</h3>
    <article class="flex justifyCenter articleHome">
         {% for livre in lastBooks %}
            <div class="livre border">
                <h3 class="center"> {{ livre.title }}</h3>
                <p class="center"> {{ livre.author }}</p>
                <br>
                {# <div class="divImg">
                    <img class="imgList" src="{{livre.img}}" alt="{{ livre.title }}">
                </div> #}
            </div>
         {% endfor %}
    </article>
    <a class="aLivres border block" href="{{ path('admin_livres')}}">Voir Tout</a>



{% endblock main %}

templates/livres.html.twig
{% extends 'base.html.twig' %}
{# j'extend mon fichier "base" pour que symfony renvoie mon squellette préalablement configuré sur cette page Html #}
{# j'ouvre mon bloc title pour signifier que cest a cet endroit que je vais modifier une donnée dans mon squelette #}
{% block title%}
    Liste de livres
{% endblock title %}
    {% block main %}
        <h2 class="center">Liste des Livres</h2>
        <article class="flex">
        {# je cree une boucle for pour passer sur chaque element de mon tableau livres et pour qu'il complete par les elements demandés #}
                {% for livre in livres %}
        <div class="livre border">
            <h3 class="center"> {{ livre.title }}</h3>
            {% if livre.author %}
              <p class="center"> {{ livre.author.firstName }} {{ livre.author.lastName }}</p>
            {% endif %}
            <em class="center date">Publié le:{{ livre.Date|date('d/m/Y')}}</em>
            <br>
          {#   <div class="divImg">
                <img class="imgList" src="{{livre.img}}" alt="{{ livre.title }}">
            </div>#}
            <a class="aLivres border block" href="{{ path('livre', {"id":livre.id}) }}">Voir Plus</a>
            <a class="aLivres border block aDelete" href="{{ path('livre_delete', {"id":livre.id}) }}">Supprimer</a>
        </div>
                {% endfor %}
        {# je referme ma boucle for #}
    </article>
        {% endblock main %}